### ISSUE TITLE
Inliner can never find CSS file

### ISSUE THREAD

**Issue by kirkbushell** [fedeisas/laravel-mail-css-inliner#201]
I've defined my CSS files in my configuration, yet when I do, it always complains about not being able to find css/email.css, for file_get_contents. Which is accurate, no such file exists for that, because it's not using the full public_path, which IS set in my config:

```php
return [
    'css-files' => [
        public_path('css/email.css')
    ]
];
```

So not sure what's going on here, but as it stands it's straight up not working.

_**Update:** I found that if you're doing this with config, you shouldn't also have a link stylesheet in your html, so I removed that, no error - but also - zero styling/inline styles. Just can't seem to get this library to work as expected._

**Comment by kirkbushell** [comment]
Coming back to this, this package just doesn't seem to work as advertised. I've tried every which way to get it working on Laravel 8, but unfortunately it never seems to find the files required.

**Comment by DannyvdSluijs** [comment]
@superbiche In an attempt to cleanup this repository I'm looking at the open issues including yours.
It seems your running into some issues. Could you provide some reproduction steps? Or at least some constraints to the version (Laravel, this library) you've been using?

**Comment by sbaum2s** [comment]
I have the same issue. Having followed this guide 

https://ralphjsmit.com/laravel-emails-tailwind-css

Maybe it would be easier to create a new laravel project just to showcase this plugin and put it on gibthub. Ultimately it looks like its either a path problem or kind of access denied. Because the file exists where the plugin tries to load it from.

**Comment by sbaum2s** [comment]
@DannyvdSluijs i created a new Laravel 8 project and upgraded it to Laravel 9. And then i followed the above mentioned guide. The reason i upgraded to Laravel 9 is, because fedeisas css inliner requires Laravel 9 and the reason i started vith Laravel 8 is, the guide uses webpack and not vite(as is used in fresh Laravel 9 projects)

So here is the github repository:

https://github.com/sbaum2s/laravel_8_inline_tailwind_with_fedeisas_css_inliner

added / changed files:

resources/views/mail/statistics.blade.php -> removed :statistics because undefined variable $subject

app/Mail/StatisticsMail.php
resources/css/mail.css
tailwind.config.js
tailwind-mail.config.js
webpack.min.js
resources/mail/base.blade.php -> moved to resources/views/mail/base.blade.php else view in Base cant find file

app/View/Components/Base.php
app/Providers/AppServiceProvider.php

I run "php artisan serve" and the actual action takes place in routes/web.php. It fails to deliver because /css/mail.css file could not be found.

Other than that to get started, of course do an "composer install" and "npm install", "npm run dev".

**Comment by ezzanox** [comment]
file_get_contents(/css/mail.css?id=0185a793cd0643ccb887f48b27d726e9): failed to open stream: No such file or directory

I'm having the same problem as above, can you help me?

**Comment by mberneis** [comment]
Have the same issue - To circumvent I changed my css include to
```
   <link rel="stylesheet" type="text/css" href="{{ public_path() . mix('css/mail.css') }}">
```
Still a bug but at least this way it does inline

**Comment by iraklisg** [comment]
> Have the same issue - To circumvent I changed my css include to
> 
> ```
>    <link rel="stylesheet" type="text/css" href="{{ public_path() . mix('css/mail.css') }}">
> ```
> 
> Still a bug but at least this way it does inline

Unfortunately, this didn't work for me

**Comment by fedeisas** [comment]
URLs are not paths. Please use a valid URL for your CSS files instead of paths.

**Comment by iampinha** [comment]
I believe we can fix this with:
`   <link rel="stylesheet" type="text/css" href="{{ asset(mix('css/mail.css')) }}">`

but the inline for me is still not good, inline styles are misplaced and not styling at all...

**Comment by darwintnt** [comment]
the same mistake in Laravel 8

<link rel="stylesheet" type="text/css" href="{{ asset('css/mail.css') }}">

"file_get_contents(http:\/\/localhost:8000\/css\/mail.css?id=1f806b33d3844536560b510120c53524): failed to open stream: Address not available"

**Comment by madeadi** [comment]
I encountered this problem too. I'm running the PHP server using `php artisan serve`. Then, I create a route. In the route handler, I call `Mail` facade to send a mailable. 

```
Route::get("/send/cop", function () {
    Mail::to("xxxi@gmail.com")->send(new ConfirmationOfPlacement());
});
```
However, I received the error: 

```
ErrorException: file_get_contents(http://localhost:8000/build/assets/mail-d4858fd2.css): Failed to open stream: 
```

The problem is because, the php configuration blocks this function `file_get_contents`. Here's the issue: https://stackoverflow.com/questions/30631972/file-get-contents-not-working-on-the-server-but-working-fine-on-local-machine.

You can configure the `php.ini` to allow a call to `file_get_contents`. However, it's a security risk. Or, when sending the email, you can use batch processing/queue. 

For me, I test this plugin using `tinker` instead of the php server. 

```
php artisan tinker

in tinker: 
> Mail::to("xxx@gmail.com")->send(new ConfirmationOfPlacement());
```

This works. 

Btw, my template file's `head` is like this: 

```
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />    
    @vite('resources/css/mail.css')
...
```

**Comment by njoguamos** [comment]
@madeadi I am experiencing the same problem when using vite.

**Comment by kirkbushell** [comment]
@fedeisas any further input on the issues above? I'm going to take another crack at it this week, as our current method has to pre-build the templates and then use purely inline styles, which is awful.

**Comment by DannyvdSluijs** [comment]
If I quickly scan the comments above it seems to revolve around two points:

1. Should you use urls or file paths: Laravel offers certain methods such as `public_path()` and `asset()` and some will return a file path and some will return a url. @fedeisas you seem to be knowledgeable on the matter maybe you could give some quick context?

2. Using `file_get_contents()` to get the contents of an url. @kirkbushell perhaps the easiest way forward is changing these for a fully fledged http call using Guzzle. This would be a more fitted approach to what we are doing. (`file_get_contents()` is the "easy"-way of getting content even when using file paths. `fopen()` and `fread()` using a `Resource` would be better in that case. As a small heads up I know that Guzzle is a dev-dependency but if we want to use it in production code we should raise it to become a main dependency.

**Comment by kirkbushell** [comment]
So I found out what the cause of the issue was, but my god did it take a while. I kept coming back to it because I couldn't find another solution for tailwind + laravel outside of this plugin.

When building emails, because of how the CSS files need to be referenced, you HAVE to build them. You can't just run npm run dev, and hope it will work - it never will, because the css files aren't accessible by css-inliner.

If you run dev, css-inliner can see the CSS files, but it's a special version of it run by vite that isn't a -real- CSS file.

Instead, you need to add a command like: npm run emails

And that command should do the following: vite build --watch

This will then build those files, write them to the disk, and you will have access to see them via css-inliner.

It would be great if this was added to the docs.

**Comment by superbiche** [comment]
@kirkbushell thanks for the workaround, this sounds like a quite logical explanation indeed.  
I'll try to give it a shot this month and come back to let you know if it works, but in the meantime thank you so much for taking the time to give those hints!

**Comment by kirkbushell** [comment]
@superbiche No problem. There may be a better solution using Vite that I'm not aware of, because having to build your files is actually a pain in the ass, and not something you really want to commit to your repository (should be built on deploy).

**Comment by fbmfbm** [comment]
Hi ,
Any solution for laravel 9 without vite (mix) ?
Thank's !

**Comment by DannyvdSluijs** [comment]
> Hi , Any solution for laravel 9 without vite (mix) ? Thank's !
Hi @fbmfbm,
As mentioned by @kirkbushell make sure the css file is available, so:
- Webserver is running (as CSS files are linked as URL's)
- The linked CSS file is accessible, you can check this using the browser

I'll close this issue for now as the problems have been resolved. Feel free to open an issue specific to your case where you provide a good description and some reproduction steps and we can take it from there.

**Comment by kirkbushell** [comment]
@DannyvdSluijs the package just needs a documentation update regarding using vite as a bundler - it literally took me 6 months since this was opened, as I kept coming back to it to try and resolve.

**Comment by kirkbushell** [comment]
@DannyvdSluijs - just FYI, this isn't really solved, you're continuing to see issues from other people. From L9 and up, Webpack is no longer what's used for builds - vite is, so the package needs to be updated to correctly load the CSS files when Vite is running in dev mode.

**Comment by sbaum2s** [comment]
I could fix the error coming from `file_get_contents()`

by changing it to

`file_get_contents(public_path() . $file)`

But even then (using Laravel MIx) it does not include the actual tailwind css definitions. In a browser it works of course as the bowser includes the link tag but not in mail.

There are several more similar plugins available, all of them on my end having the same file_get_contents problem and at the end of the story still no included CSS. So i´m still on it trying to figure out what the actual issue is.

**Comment by kirkbushell** [comment]
The issue is that Vite provides like a "virtual" CSS file, and this isn't able to be loaded when generating email content. So you have to build the CSS files to make that run properly.

This package needs to adjust how it loads the CSS depending upon the Vite state - ie. Is it running in production and therefore the CSS files are available, or is it running in development where the CSS files are essentially generated as required (no actual file on disk).

@DannyvdSluijs Again, this issue isn't closed and requires some changes to the CSS loading, as this hasn't been updated since webpack and has been broken since at least laravel 8.

**Comment by DannyvdSluijs** [comment]
I haven’t been actively involved with the project for a long time. Currently I’m not even working with the Laravel framework. 

@kirkbushell you remarks seem valid. Would you say you would be able to draft a PR? I could still review, merge and release if needed. However I can’t make the time to create the PR myself.
